config/routes.rb
Rails.application.routes.draw do
  root to: 'static#default_project'
  
  resources :users, only: %w(new create)
  get 'sign_up' => 'users#new', as: :sign_up

  resources :projects do
    member do
      get :card
    end
    resources :posts
    resources :public_posts, only: :index
    resources :authors, only: :index do
      collection do
        get :index_card
      end
    end
  end
  
  resources :posts do
    member do
      get :card
      post :check_for_plagiarism
    end
  end

  resources :public_posts, only: :index

  resource :account, only: %w(edit update destroy)
  resource :session, only: %w(new create destroy)
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out

  get 'dashboard' => 'static#dashboard', as: :dashboard
  get 'faq' => 'static#faq', as: :faq
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :posts, dependent: :restrict_with_error
  has_many :editing_users, through: :posts
  has_many :memberships
  has_many :members, through: :memberships, source: :user
  
  validates_presence_of :code
  validates_uniqueness_of :code
  validates_presence_of :feature_duration_in_days
  
  scope :has_posts, -> { where(id: Post.passed(false).select(:project_id)) }
  
  def to_param
    "#{id}-#{code.to_s.parameterize}"
  end
  
  def cache_key
    [
      to_param, updated_at, posts.maximum(:updated_at),
      editing_users.maximum(:updated_at), memberships.maximum(:updated_at)
    ]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_user_has_membership, only: [:update, :destroy]
  
  respond_to :js
  
  def index
    @projects = Project.all
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def card
    @project = Project.find(params[:id])
    
    render 'card', layout: nil
  end
  
  def new
    @project = Project.new
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def create
    @project = Project.new(project_params)
    
    if @project.save
      @project.members << current_user unless @project.members.include? current_user
      return_or_redirect_to projects_url, notice: 'Project created.'
    else
      render 'new'
    end
  end
  
  def update
    @project = Project.find(params[:id])
    
    if @project.update_attributes(project_params)
      return_or_redirect_to projects_url, notice: 'Project updated.'
    else
      render 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    
    if @project.destroy
      respond_to do |format|
        format.html { return_or_redirect_to projects_url, notice: 'Project deleted.' }
        format.js
      end
    else
      respond_to do |format|
        format.html { return_or_redirect_to projects_url, flash: { error: @project.errors.full_messages.first } }
        format.js
      end
    end
  end
private
  def project_params
    attributes = [:name, :code, :feature_duration_in_days, member_ids: []]

    params.require(:project).permit *attributes
  end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  .container
    .row
      .col-sm-3
      .col-sm-6
        - if @project.errors.any?
          %form-errors{data: {errors: @project.errors.full_messages.to_json}}
        %fieldset.form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
          %small.text-muted E.g.: Sandbox
        %fieldset.form-group
          = f.label :code
          = f.text_field :code, class: 'form-control'
        %fieldset.form-group
          = f.label :feature_duration_in_days
          = f.number_field :feature_duration_in_days, class: 'form-control'
        %fieldset.form-group
          = f.label :members
          = select_tag 'project[member_ids]', options_for_select(User.all.map { |u| [u.nick, u.id] }, @project.member_ids),
            multiple: true,
            class: 'form-control form-control-sm', data: {chosen: true}
        %fieldset.form-group
          = f.submit class: 'btn btn-primary'
          = link_to 'Back', projects_path, class: 'btn btn-info pull-xs-right'
      .col-sm-3

app/views/projects/_project.html.haml
- posts = project.posts.this_week

.card
  .card-block
    .card-title
      %strong= project.name
      .pull-xs-right
        %small
          Members:
          = project.members.count
  %ul.list-group.list-group-flush
    %li.list-group-item
      code: 
      %code= project.code
        
  .card-block
    = link_to "Posts (#{posts.count})", project_posts_path(project), class: 'btn btn-primary btn-sm', uib_tooltip: project_stats(project, posts)
    - if current_user_has_membership?(project)
      = link_to 'Edit', edit_project_path(project), class: 'btn btn-info btn-sm card-link'
      = link_to 'Delete', project_path(project), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm card-link pull-xs-right'

app/views/projects/card.html.haml
- cache @project.cache_key do
  =render partial: 'project', object: @project, as: :project

app/views/projects/edit.html.haml
Edit Project
= render partial: 'form'

app/views/projects/index.html.haml
%h1 Projects
.row
  .col-sm-12
    - @projects.each do |project|
      %project_card{data: {type: 'projects', project_id: project.id}}
.row
  .col-sm-12
    = link_to 'Back', dashboard_path, class: 'btn btn-info btn-sm'
    = link_to 'New', new_project_path, class: 'btn btn-info btn-sm'

app/views/projects/new.html.haml
New Project
= render partial: 'form'

app/views/projects/show.html.haml
.jumbotron.bg-faded
  %project_card{data: {type: 'projects', project_id: @project.id}}
  
= link_to 'Back', projects_path, class: 'btn btn-primary'