config/routes.rb
Rails.application.routes.draw do
  root to: 'static#default_project'
  
  resources :users, only: %w(new create)
  get 'sign_up' => 'users#new', as: :sign_up

  resources :projects do
    member do
      get :card
    end
    resources :posts
    resources :public_posts, only: :index
    resources :authors, only: :index do
      collection do
        get :index_card
      end
    end
  end
  
  resources :posts do
    member do
      get :card
      post :check_for_plagiarism
    end
  end

  resources :public_posts, only: :index

  resource :account, only: %w(edit update destroy)
  resource :session, only: %w(new create destroy)
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out

  get 'dashboard' => 'static#dashboard', as: :dashboard
  get 'faq' => 'static#faq', as: :faq
end

app/controllers/public_posts_controller.rb
class PublicPostsController < ApplicationController
  skip_before_action :authorize_user!
  respond_to :js, :json
  
  def index
    sort_field = params[:sort_field] || 'created_at'
    sort_order = params[:sort_order] || 'desc'
    @project = Project.find params[:project_id]
    cooldown_days = @project.feature_duration_in_days
    cooldown = cooldown_days.days.ago
    @posts = @project.posts.published.where('posts.created_at > ?', cooldown)
    
    @posts = if sort_field == 'active_votes'
      @posts.order_by_active_votes(direction: sort_order)
    elsif sort_field == 'pending_payout_value'
      @posts.order_by_pending_payout_value(direction: sort_order)
    elsif sort_field == 'best_payout_value'
      @posts.order_by_best_payout_value(direction: sort_order)
    else
      @posts.ordered(by: sort_field, direction: sort_order)
    end
  end
end

app/helpers/public_posts_helper.rb
module PublicPostsHelper
  def public_posts_table_row_class(post)
    if post.published? && post.rejected?
      'table-danger'
    else
      nil
    end
  end
  
  def public_post_detailed_payout(post)
    payouts = []
    c = post.content
    
    (v = c.total_payout_value) != '0.000 SBD' and payouts << "Author: #{v}"
    (v = c.curator_payout_value) != '0.000 SBD' and payouts << "Curator: #{v}"
    (v = c.pending_payout_value) != '0.000 SBD' and payouts << "Pending: #{v}"
    (v = c.total_pending_payout_value) != '0.000 SBD' and payouts << "Total Pending: #{v}"
      
    payouts.join("; ").gsub(' SBD', '') + ' (SBD)'
  end
end

app/views/public_posts/_post.html.haml
%tr{uib_tooltip: post.notes, class: public_posts_table_row_class(post)}
  %td
    - if post.published? && post.rejected?
      .glyphicon.glyphicon-flag
    - else
      .glyphicon.glyphicon-ok
  %td= link_to post.steem_author, "https://steemit.com/@#{post.steem_author}"
  %td
    %relative_timestamp= post.created_at.iso8601
  %td
    %span{uib_tooltip: public_post_detailed_payout(post)}
      = post.best_payout_value_formatted
  %td= post.content.active_votes.size
  %td
    - if post.rejected? && !!post.notes
      = link_to truncate(post.title, length: 75), post.canonical_url,
        data: { confirm: post.notes }
    - else
      = link_to truncate(post.title, length: 75), post.canonical_url

app/views/public_posts/index.html.haml
= content_for :head, auto_discovery_link_tag(:atom, "http://#{public_posts_url(project_id: @project.id, format: :atom).split('://')[1]}")

%h1= @project.name

- cache ['public-project', params, @project] do
  %table.table.table-sm.table-striped
    %thead.thead-inverse
      %tr
        %th{scope: :row}
        %th{scope: :row}= sortable_header_link_to 'Author', 'steem_author'
        %th{scope: :row}= sortable_header_link_to 'Added', 'created_at'
        %th{scope: :row}= sortable_header_link_to 'Payment', 'best_payout_value'
        %th{scope: :row}= sortable_header_link_to 'Votes', 'active_votes'
        %th{scope: :row} Post
      %tbody
        - @posts.each do |post|
          - cache ['public-project-post', post] do
            = render partial: 'post', object: post, as: :post