config/routes.rb
Rails.application.routes.draw do
  root to: 'static#default_project'
  
  resources :users, only: %w(new create)
  get 'sign_up' => 'users#new', as: :sign_up

  resources :projects do
    member do
      get :card
    end
    resources :posts
    resources :public_posts, only: :index
    resources :authors, only: :index do
      collection do
        get :index_card
      end
    end
  end
  
  resources :posts do
    member do
      get :card
      post :check_for_plagiarism
    end
  end

  resources :public_posts, only: :index

  resource :account, only: %w(edit update destroy)
  resource :session, only: %w(new create destroy)
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out

  get 'dashboard' => 'static#dashboard', as: :dashboard
  get 'faq' => 'static#faq', as: :faq
end

app/models/post.rb
include ActionView::Helpers::DateHelper

class Post < ActiveRecord::Base
  ALLOWED_STATUS = %w(proposed submitted accepted rejected passed)
  HUMANIZED_ATTRIBUTES = {
    slug: 'Permalink'
  }

  belongs_to :project
  belongs_to :editing_user, class_name: 'User', foreign_key: :editing_user_id
  
  validates :status, inclusion: { in: ALLOWED_STATUS }
  validates_uniqueness_of :slug, scope: :project
  validates_format_of :slug, with: /@[a-z0-9\-\.]+\/.*/
  validate :author_cooldown
  validate :on_blockchain, if: :slug_changed?

  scope :status, lambda { |status_name, status = true|
    where(status: status_name).tap do |r|
      return status ? r : where.not(id: r.select(:id))
    end
  }

  scope :proposed, lambda { |proposed = true| status 'proposed', proposed }
  scope :submitted, lambda { |submitted = true| status 'submitted', submitted }
  scope :accepted, lambda { |accepted = true| status 'accepted', accepted }
  scope :rejected, lambda { |rejected = true| status 'rejected', rejected }
  scope :passed, lambda { |passed = true| status 'passed', passed }
  
  scope :published, lambda { |published = true| where published: published }
  
  scope :this_week, -> { where("posts.created_at > ?", Time.now.beginning_of_week.advance(days: -1)) }
  scope :this_month, -> { where("posts.created_at > ?", Time.now.beginning_of_month) }
  
  scope :in_cooldown, lambda { |author, cooldown|
    published.where(steem_author: author).created(cooldown)
  }
  
  scope :created, lambda { |date, created = true|
    where('posts.created_at > ?', date).tap do |r|
      return created ? r : where.not(id: r.select(:id))
    end
  }
  scope :today, lambda { created(Time.now.beginning_of_day) }
  
  scope :ordered, lambda { |options = {by: :created_at, direction: 'asc'}|
    options[:by] ||= :created_at
    options[:direction] ||= 'asc'
    order(options[:by] => options[:direction])
  }
  
  scope :query, lambda { |query|
    where("LOWER(posts.content_cache) LIKE ?", "%#{query.downcase}%")
  }
  
  scope :steem_mode, lambda { |mode, invert = false|
    where('posts.content_cache LIKE ?', "%\"mode\":\"#{mode}\"%").tap do |r|
      return invert ? r : where.not(id: r.select(:id))
    end
  }
  
  scope :steem_first_payout, lambda { |first_payout = true|
    steem_mode('first_payout', first_payout)
  } 
  
  scope :steem_second_payout, lambda { |second_payout = true|
    steem_mode('second_payout', second_payout)
  } 
  
  scope :steem_archived, lambda { |archived = true|
    steem_mode('archived', archived)
  } 
  
  def self.human_attribute_name ( attr, options = {} )
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  after_validation do
    ContentGetterJob.perform_later(id) unless Rails.env.test?
  end
  
  after_save do
    fix_booleans
  end
  
  def self.order_by_active_votes(options = {direction: 'asc'})
    posts = all.sort_by do |post|
      post.content.active_votes.size
    end
    
    if options[:direction] == 'desc'
      posts = posts.reverse
    end
    
    posts
  end

  def self.order_by_pending_payout_value(options = {direction: 'asc'})
    posts = all.sort_by do |post|
      post.content.pending_payout_value.split(' ').first
    end
    
    if options[:direction] == 'desc'
      posts = posts.reverse
    end
    
    posts
  end
  
  def self.order_by_best_payout_value(options = {direction: 'asc'})
    posts = all.sort_by do |post|
      post.best_payout_value
    end
    
    if options[:direction] == 'desc'
      posts = posts.reverse
    end
    
    posts
  end
  
  def self.deactivate_all!
    update_all("status = 'passed'")
  end
  
  def to_param
    "#{id}-#{slug.to_s.parameterize}"
  end
  
  def proposed?
    status == 'proposed'
  end
  
  def submitted?
    status == 'submitted'
  end
  
  def accepted?
    status == 'accepted'
  end
  
  def rejected?
    status == 'rejected'
  end
  
  def passed?
    status == 'passed'
  end
  
  def steem_first_payout?
    Post.steem_first_payout.include? self
  end
  
  def steem_second_payout?
    Post.steem_second_payout.include? self
  end
  
  def steem_archived?
    Post.steem_archived.include? self
  end
  
  def author_cooldown
    if errors.empty?
      author = slug.split('/').first.split('@').last
      cooldown_days = project.feature_duration_in_days
      cooldown = cooldown_days.days.ago
      posts = project.posts.where.not(id: self).in_cooldown(author, cooldown)
      
      if !!author && published? && posts.any?
        post = posts.ordered.last
        words = time_ago_in_words(post.created_at)
        error_message = <<-DONE
          This project has a #{cooldown_days} day feature limit and @#{author}
          has already been featured #{words} ago.
        DONE
        errors.add(:base, error_message)
      end
    end
  end
  
  def on_blockchain
    if errors.empty?
      errors.add(:slug, 'This post not found in blockchain.') unless content?
    end
  end
  
  def canonical_url
    "https://steemit.com#{steem_url}"
  end
  
  def content
    if content_cache.nil?
      api = Radiator::Api.new(RADIATOR_OPTIONS)
      author = slug.split('/').first.split('@').last
      permlink = slug.split('/')[1..-1].join
      content = api.get_content(author, permlink).result
      self.content_cache = content.to_json
      self.content_cached_at = Time.now
      self.steem_id ||= content.id
      self.steem_author ||= content.author
      self.steem_permlink ||= content.permlink
      self.steem_category ||= content.category
      self.steem_parent_permlink ||= content.parent_permlink
      self.steem_created ||= content.created
      self.steem_url ||= content.url
      save
    end
    
    Hashie::Mash.new(JSON[content_cache])
  end
  
  def content!
    self.content_cache = nil
    self.content_cached_at = nil
    self.steem_id = nil
    self.steem_author = nil
    self.steem_permlink = nil
    self.steem_category = nil
    self.steem_parent_permlink = nil
    self.steem_created = nil
    self.steem_url = nil
    content
  end
  
  def content?
    content.id != '0.0.0'
  end
  
  def title
    content.title.empty? ? slug : content.title
  end
  
  def best_payout_value
    @best_payout_value if !!@best_payout_value
    
    total = content.total_payout_value.split(' ').first.to_f
    curator = content.curator_payout_value.split(' ').first.to_f
    pending = content.pending_payout_value.split(' ').first.to_f
    total_pending = content.total_pending_payout_value.split(' ').first.to_f
    
    @best_payout_value = [past = total + curator, total_pending].max
  end

  def best_payout_value_formatted
    "$%.2f" % best_payout_value
  end
  
  def voters_sorted_by_weight
    @voters_sorted_by_weight ||= content.active_votes.to_a.sort_by { |v| v.weight.to_i.abs }
  end

  def top_voter
    @top_voter ||= voters_sorted_by_weight.last
  end
  
  def top_voter_account
    top_voter.first.last rescue nil
  end
  
  def plagiarism_checked?
    !!plagiarism_checked_at
  end
  
  def cache_key
    [to_param, updated_at, project.updated_at, editing_user.cache_key]
  end
private
  # Fix booleans for SQLite.  See: https://kconrails.com/2008/07/18/ruby-on-rails-bool-vs-boolean-in-sqlite3/
  def fix_booleans
    Post.where.not(published: 't').update_all("published = 'f'")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_user_has_membership, only: [:create, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :check_for_plagiarism
  respond_to :js, :json
  before_action :init_params, only: :index
  
  def index
    @posts = if !!@project
      @project.posts.this_week
    else
      Post.all.this_week
    end
    
    @posts = @posts.query(@query) if @query.present?
    @posts = @posts.where(status: @status) if @status.present?
    @posts = @posts.published(@published == 'true') if @published.present?
    @posts = @posts.limit(@limit) if @limit.present?
    
    if @sort_field.present?
      @posts = @posts.ordered(by: @sort_field, direction: @sort_order)
    end
  end
  
  def show
    @post = Post.find params[:id]
  end
  
  def card
    @post = Post.find(params[:id])
    
    render 'card', layout: nil
  end
  
  def new
    @post = Post.new(status: 'submitted', editing_user: current_user, project_id: params[:project_id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params.merge(editing_user: current_user))
    
    if @post.save
      return_or_redirect_to project_post_url(@post.project, @post), notice: 'Post created.'
    else
      render 'new'
    end
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update_attributes(post_params)
      return_or_redirect_to project_post_url(@post.project, @post), notice: 'Post updated.'
    else
      render 'edit'
    end
  end
  
  def check_for_plagiarism
    @post = Post.find(params[:id])
    
    if !!@post.plagiarism_results_url
      Rails.logger.info "Skipped Plagiarism check, reusing last result."
      respond_to do |format|
        format.html {
          redirect_to search.results_url
        }
        format.json
      end
      
      return
    end
    
    search = Plagiarism.text_search(@post.content.body)
    Rails.logger.info "Plagiarism results; count: #{search.count}, words: #{search.words}, url: #{search.results_url}"
    @post.update_attributes(plagiarism_results_url: search.results_url, plagiarism_checked_at: Time.now)
    
    if search.success? && search.results?
      respond_to do |format|
        format.html {
          redirect_to search.results_url
        }
        format.json
      end
    else
      if !!(@error = search.response.response['response']['error'])
        respond_to do |format|
          format.html {
            return_or_redirect_to project_post_url(@post.project, @post), flash: { error: "Error: #{@error}" }
          }
          format.json
        end
      else
        respond_to do |format|
          format.html {
            return_or_redirect_to project_post_url(@post.project, @post), notice: "No plagiarism found."
          }
          format.json
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      respond_to do |format|
        format.html { return_or_redirect_to project_posts_url(@post.project), notice: 'Post deleted.' }
        format.js
      end
    end
  end
private
  def post_params
    attributes = [:status, :slug, :project_id, :status, :notes, :published]
    
    params.require(:post).permit *attributes
  end
  
  def init_params
    @project_id = session[:posts_project_id]
    @sort_field = session[:posts_sort_field]
    @sort_order = session[:posts_sort_order]
    @query = session[:posts_query]
    @status = session[:posts_status]
    @published = session[:posts_published]
    @limit = session[:posts_limit]
    
    @project = Project.find params[:project_id] if params[:project_id]
    
    if !!params[:sort_field] || !!params[:sort_order] || !!params[:query] ||
      !!params[:status] || !!params[:published] || !!params[:limit]
      @sort_field = params[:sort_field]
      @sort_order = params[:sort_order]
      @query = params[:query]
      @status = params[:status]
      @published = params[:published]
      @limit = params[:limit]
    end
    
    session[:posts_project_id] = @project_id
    session[:posts_sort_field] = @sort_field
    session[:posts_sort_order] = @sort_order
    session[:posts_query] = @query
    session[:posts_status] = @status
    session[:posts_published] = @published
    session[:posts_limit] = @limit
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_card_class(post)
    if post.rejected?
      'card-outline-danger'
    elsif post.steem_first_payout?
      'card-outline-primary'
    elsif post.steem_second_payout?
      'card-outline-secondary'
    elsif post.steem_archived?
      'card-outline-secondary'
    end
  end
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.hidden_field :project_id, ng_model: 'project_id', splatnit: true

  .container{ng_controller: 'PostLookupCtrl'}
    .row
      .col-sm-12
        - if @post.errors.any?
          %form-errors{data: {errors: @post.errors.full_messages.to_json}}
    .row
      .col-sm-12
        %fieldset.form-group{ng_class: "{'has-warning' : !!slug_warning}"}
          -# = f.label :slug, 'URL/Permlink'
          -# %button.label.label-pill.label-info.pull-xs-right{ng_if: '!!slug', ng_click: 'loadItemDetails($event)'}
          -#   Fetch Post
          = f.text_field :slug, class: 'form-control', autofocus: true, ng_model: 'slug', splatnit: true
          %small.text-muted
            You can paste a steemit URL here.
            %span{ng_if: '!!slug_warning'}
              .alert.alert-warning {{slug_warning}}
    .row
      .col-sm-12
        %fieldset.form-group
          = f.label :status
          = f.select :status, Post::ALLOWED_STATUS, { include_blank: false },
            class: 'form-control form-control-sm', data: {chosen: true},
            ng_model: 'status', splatnit: true
    .row
      .col-sm-12
        %fieldset.form-group
          = f.label :notes, 'Notes'
          = f.text_area :notes, class: 'form-control', ng_model: 'notes', splatnit: true
          .small.alert.alert-warning{ng_show: "!!notes"}
            Keep in mind, notes are public.  They appear as tool tips on the
            public page.  If a post is ever rejected + published, these notes
            will also appear as a dialog when the user clicks on the link on
            the public page.
    .row
      .col-sm-12
        = f.select :published, [['published', true], ['unpublshed', false]], { include_blank: false },
          class: 'form-control form-control-sm', data: {chosen: true},
          ng_model: 'published', splatnit: true
        .small.alert.alert-warning{ng_show: "publishWarning()"}
          Typically, a post should only be published if the status is:
          %code accepted
    .row
      .col-sm-12
        %fieldset.form-group
    .row
      .col-sm-12
        %fieldset.form-group
          - if !!@post.project
            - if @post.persisted?
              = f.submit 'Save', class: 'btn btn-primary'
            - else
              = f.submit 'Create', class: 'btn btn-primary'
            = link_to 'Cancel', project_posts_path(@post.project_id), class: 'btn btn-info'
          - else
            = f.submit class: 'btn btn-primary'
            = link_to 'Cancel', posts_path, class: 'btn btn-info'

app/views/posts/_post.html.haml
.card{ng_controller: 'PostCardCtrl',
in_view_container: true,
in_view: 'showCard ? showCard : showCard = $inview',
in_view_options: '{ debounce: 100 }',
class: post_card_class(post)}
  .card-block
    .card-title
      .list-group-item-heading
        %strong
          = link_to post.title, post.canonical_url
          - if post.rejected?
            %span.tag.tag-danger.glyphicon.glyphicon-flag (Rejected)
        .pull-xs-right.nga-default.nga-stagger-slow.nga-fade{ng_if: 'showCard'}
          %small
            Post by:
            = link_to "@#{post.steem_author}", "https://steemit.com/@#{post.steem_author}"
            %br
            Added by:
            = post.editing_user.nick
            = surround '(', ')' do
              %relative_timestamp= post.created_at.iso8601
      %p.list-group-item-text
        = post.steem_category
  - if post.content?
    %ul.list-group.list-group-flush.nga-fast.nga-rotate-up{ng_if: 'showCard'}
      %li.list-group-item
        %span
          Total Payout:
          = post.content.total_payout_value
          |
        %span
          Pending Payout:
          = post.content.pending_payout_value
          |
        %span
          Votes:
          = post.content.active_votes.size
        - if !!post.top_voter_account
          |
          %span
            Top Vote:
            %abbr{uib_tooltip: post.voters_sorted_by_weight.last(10).reverse.map(&:voter).join(' ') + ' ...'}
              = post.top_voter_account
              = surround '(', ')' do
                = "%.2f%" % (post.top_voter.percent.to_f / 100)
        %small.pull-xs-right
          Posted:
          %relative_timestamp= post.steem_created + 'Z'
  - if !!post.notes
    .card-block
      .list-group-item-text
        %p= post.notes
            
  .card-block
    .row
      .col-sm-6
        .btn-group
          - if current_user_has_membership?(post.project)
            = link_to 'Edit', edit_project_post_path(post.project, post), class: 'btn btn-info btn-sm card-link'
        - if post.plagiarism_checked? && !!post.plagiarism_results_url
          = link_to "Plagiarism Results",
          post.plagiarism_results_url,
          class: 'btn btn-info btn-sm card-link',
          ng_click: "modalPlagiarismResults($event, #{post.id}, '#{post.plagiarism_results_url}', '#{post.plagiarism_checked_at}')"
        - elsif defined?(Plagiarism) && !!Plagiarism.username
          = link_to "Plagiarism Check",
          check_for_plagiarism_post_path(post),
          class: 'btn btn-info btn-sm card-link',
          uib_tooltip: copyscape_credit_balance,
          ng_click: "modalPlagiarismResults($event, #{post.id}, '#{post.plagiarism_results_url}', '#{post.plagiarism_checked_at}')"
      .col-sm-6
        .pull-xs-right.btn-group
          - if current_user_has_membership?(post.project)
            = link_to 'Delete', project_post_path(post.project, post), method: :delete, data: {confirm: 'Are you sure?', remote: true}, class: 'btn btn-danger btn-sm card-link'

%script{id: "modal_plagiarism_results.html", type: "text/ng-template"}
  .modal-body.large
    %span{ng_bind_html: 'plagiarism_results'}
  .modal-footer
    %button.btn.btn-warning{ng_click: "done()", type: "button"} Done

app/views/posts/_query.html.haml
%hr
.row
  .col-sm-3
    %h3
      = pluralize @posts.except(:select).count, 'Post'
      (this week)

  .col-sm-9
    = form_tag url_for(action: controller.action_name), method: :get do
      .row
        .col-sm-12
          .input-group
            .input-group-addon Query
            = text_field_tag :query, @query, placeholder: 'Query Text',
            class: 'form-control form-control'
      .row
        .col-sm-6
          .input-group
            .input-group-addon Status
            = select_tag :status, options_for_select([['', nil]] + Post::ALLOWED_STATUS, @status),
            class: 'form-control'
        .col-sm-6
          .input-group
            .input-group-addon Published
            = select_tag :published, options_for_select([['', nil], ["Yes", true], ["No", false]], @published),
            class: 'form-control'
      .row
        .col-sm-9
          .input-group
            .input-group-addon Limit
            = number_field_tag :limit, @limit, placeholder: 'Limit',
            maxlength: 4, class: 'form-control form-control'
        .col-sm-3= submit_tag 'Search',
        class: 'btn btn-info btn form-control form-control'

app/views/posts/card.html.haml
- cache ['post-card', params, @post.cache_key] do
  =render partial: 'post', object: @post, as: :post
  

app/views/posts/edit.html.haml
%h1 Edit Post
= render partial: 'form'

app/views/posts/index.html.haml
- cache ['posts-query', params, (!!@project ? @project.cache_key : Time.now)] do
  = render partial: 'query'
  
.row
  .col-sm-12
    %hr
.row
  .col-sm-12
    - @posts.each do |post|
      %post_card{data: {post_id: post.id}}

.row
  .col-sm-12
    = link_to 'Back', projects_path(@project), class: 'btn btn-info btn-sm'
    - if !!@project && current_user_has_membership?(@project)
      = link_to 'New', new_project_post_path(@project), class: 'btn btn-info btn-sm'

app/views/posts/new.html.haml
%h1 New Post
= render partial: 'form'

app/views/posts/show.html.haml
.jumbotron.bg-faded
  %post_card{data: {post_id: @post.id}}
  
= link_to 'Back', project_posts_path(@post.project_id), class: 'btn btn-primary'
= link_to 'Create Another', new_project_post_path(@post.project_id), class: 'btn btn-primary'