config/routes.rb
Rails.application.routes.draw do
  root to: 'static#default_project'
  
  resources :users, only: %w(new create)
  get 'sign_up' => 'users#new', as: :sign_up

  resources :projects do
    member do
      get :card
    end
    resources :posts
    resources :public_posts, only: :index
    resources :authors, only: :index do
      collection do
        get :index_card
      end
    end
  end
  
  resources :posts do
    member do
      get :card
      post :check_for_plagiarism
    end
  end

  resources :public_posts, only: :index

  resource :account, only: %w(edit update destroy)
  resource :session, only: %w(new create destroy)
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out

  get 'dashboard' => 'static#dashboard', as: :dashboard
  get 'faq' => 'static#faq', as: :faq
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sherwood
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: :viewport, content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no'}
    %meta{name: 'apple-mobile-web-app-capable', content: :yes}
    %link{href: '/favicon.ico', rel: 'shortcut icon', type: 'image/x-icon'}
    = yield :head
  %body
    .container-fluid
      %nav.navbar.navbar-fixed-top.navbar-light.bg-faded
        .container-fluid
          %span.pull-xs-right &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          - if current_user
            .dropdown.pull-xs-right
              %a.nav-link.dropdown-toggle{data: {toggle: :dropdown}, href: '#', uib_tooltip: current_user.email, tooltip_placement: 'left'}
                =current_user.nick
              .dropdown-menu
                .dropdown-item
                  %span.glyphicon.glyphicon-dashboard
                  = link_to "Dashboard", dashboard_path
                - if !!current_project
                  .dropdown-item
                    = form_tag project_posts_path(current_project), method: :get, class: 'form-inline' do
                      = hidden_field_tag :limit, 10
                      .form-group
                        %span.glyphicon.glyphicon-search
                        = text_field_tag :query, '', placeholder: 'Quick Query', class: 'form-control form-control-sm'
                  .dropdown-item
                    %span.glyphicon.glyphicon-plus
                    = link_to "New Post", new_project_post_path(current_project)
                .dropdown-item
                  %span.glyphicon.glyphicon-thumbs-up
                  = link_to "Public Posts", public_posts_path(project_id: current_project)
                .dropdown-divider
                .dropdown-item
                  %span.glyphicon.glyphicon-edit
                  = link_to "Edit Account", edit_account_path
                .dropdown-item
                  %span.glyphicon.glyphicon-minus-sign
                  = link_to "Log out", log_out_path
          - elsif controller_name != 'public_posts'
            %ul.nav.navbar-nav.pull-xs-right
              %li.nav-item
                = link_to sign_up_path, class: 'nav-link', uib_tooltip: 'Sign up so you can do the thing.', tooltip_placement: 'left' do
                  %span.glyphicon.glyphicon-user
                  Sign Up
              %li.nav-item
                = link_to log_in_path, class: 'nav-link', uib_tooltip: 'You can do the thing if you already have an account.', tooltip_placement: 'left' do
                  %span.glyphicon.glyphicon-plus-sign
                  Log In
          - else
            %p &nbsp;
    .row.col-sm-12
      %hr
      %hr
    .row
      .col-sm-12
        .alert-container
          %flash{'flash-message' => 5000, data: {messages: flash.to_json}}
        .container
          = yield

app/views/layouts/card.html.haml
%div=yield